# Telegram Chat Bot
:doctype: article
:toc: right
:copyright: © 2021

:toc:

{copyright} {author}

This bot will start out with telegram, but may expand to allow for e-mail
subscription requests for newsletters, price updates, and reports.

# Operation
## Create a bot using the front-end editor
The Bot ID will be shown on the home page or bot configuration page

## Connect telegram to webhook:
### Webhook URL:
```
https://<AWS SUBDOMAIN>.execute-api.us-east-1.amazonaws.com/bot/<TELEGRAM BOT TOKEN>/update/<BOT CONFIGURATION ID>
```

### Register webhook with telegram
```
  curl --request POST 'https://api.telegram.org/bot<TELEGRAM_TOKEN>/setWebhook' \
  --header 'content-type: application/json' \
  --data '{
    "url": "<WEBHOOK_URL>"
  }'
```

## Configure the bot
Create commands in the front end editor for the bot. Further documentation can be found there.

## Announcements
You can send messages to any user or channel using the announce endpoint.
```
curl --request POST 'https://<AWS SUBDOMAIN>.execute-api.us-east-1.amazonaws.com/bot/<TELEGRAM BOT TOKEN>/announce' \
--header 'Content-Type: application/json' \
--data-raw '{
  "channel": "@<CHANNEL OR USER NAME>",
  "message": "<MESSAGE TO SEND>"
}'
```
For channels, the bot must be in the channel. For users the user must have previously sent /start to the bot.

# Development

## Set Up

- Clone the repository
- Run ```amplify configure project```

### Vue Project setup

```
npm install
```

#### Compiles and hot-reloads for development

```
npm run serve
```

#### Compiles and minifies for production

```
npm run build
```

#### Lints and fixes files

```
npm run lint
```

#### Customize configuration

See link:https://cli.vuejs.org/config/[Configuration Reference].

## Amplify

### status

```
amplify status
```

### Push Backend

```
amplify push
```

### Build and Deploy Frontend

```
amplify publish
```

### Modify a Backend Resource

```
amplify [create|update|remove] [resource type]
```
