# Euler Chat Bot
Euler Tools
:doctype: article
:toc: right
:copyright: © 2021

:toc:

{copyright} {author}

This bot will start out with telegram, but may expand to allow for e-mail
subscription requests for newsletters, price updates, and reports.

# Operation
## Create a bot using the front-end editor
The Bot ID will be shown on the home page or bot configuration page

## Connect telegram to webhook:
- Webhook URL:
  ```
  https://<AWS SUBDOMAIN>.execute-api.us-east-1.amazonaws.com/bot/<TELEGRAM BOT TOKEN>/update/<BOT CONFIGURATION ID>
  ```
- Register webhook with telegram
  ```bash
    curl --request POST 'https://api.telegram.org/bot<TELEGRAM_TOKEN>/setWebhook' \
    --header 'content-type: application/json' \
    --data '{
      "url": "<WEBHOOK_URL>"
    }'
  ```
## Configure the bot
Create commands in the front end editor for the bot. Further documentation can be found there.

## Announcements
You can send messages to any user or channel using the announce endpoint.
```
curl --request POST 'https://<AWS SUBDOMAIN>.execute-api.us-east-1.amazonaws.com/bot/<TELEGRAM BOT TOKEN>/announce' \
--header 'Content-Type: application/json' \
--data-raw '{
  "channel": "@<CHANNEL OR USER NAME>",
  "message": "<MESSAGE TO SEND>"
}'
```
For channels, the bot must be in the channel. For users the user must have previously sent /start to the bot.

# Proposed Commands

## Live request triggers community

* `/price` gets a pair price
* `/pool` gets the pool information
* `/scam` as reply to a message will check our database and search for the
  message content, maybe is a fake contract.
** It can take an option that the
   report also bans the author from all channels with our bot. User will receive
   a message in which they can open a support ticket to remove the ban.

## Announcement and Subscript Functionality

* `/subscribe` can suscribe to a pair and start receiving price notifications
* `/alerts` can subscribe to a pair and receive alerts, like liquidity draining
* `/remind` sends periodic messages to the channel
* `/twitter` can subscribe to a twitter user and share his tweets (good to gain RT)

# Development

As we know what is needed to build the commands, we will write that in Postman
so the platform team can get those connections done. Meaning, the API's will be
developed to accommodate what is wanted here.

### Jira integration

To help with connecting branches and pull pull requests in Jira, the following

..git/COMMIT_TEMPLATE
[source, text]
----
Short Description

Long description here.

# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

# An example of JIRA integration via this comment message can be:

BOTS-1     #time 2h 15m     #done

It follows the following pattern.

<ISSUE_KEY> #<COMMAND_1> <optional COMMAND_1_ARGUMENTS> #<COMMAND_2> <optional COMMAND_2_ARGUMENTS> ... #<COMMAND_n> <optional COMMAND_n_ARGUMENTS>

See https://support.atlassian.com/bitbucket-cloud/docs/use-smart-commits/ for
additional details.
----

Configure the project with the following command at the terminal:

`git config commit.template ./.git/COMMIT_TEMPLATE`

Once that is done, for each branch that you create that is tied to a Jira
ticket, you would have the following pattern:

`git checkout -b BOT-3_description_here_if_you_want`

include::./front-end/README.md[offset=+1]

# Copyrights and Licenses

This document is {copyright} {author}.

Portions of this software is copyright and licensed as found in various LICENSE
files.
